# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# 01 12 * * * 表示中国北京时间每天晚上8点01分执行，github采用的是utc时间也就是英国伦敦时区，我们是正8区，所以要减8个小时
name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 18 01 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: autoReport
        run: |
          python main.py
        env:
          accessToken: ${{ secrets.ACCESSTOKEN }}
          secret: ${{ secrets.SECRET }}
          latitude: ${{ secrets.LATITUDE }}
          longitude: ${{ secrets.LONGITUDE }}
          province: ${{ secrets.PROVINCE }}
          city: ${{ secrets.CITY }}
          area: ${{ secrets.AREA }}
          address: ${{ secrets.ADDRESS }}
